### ISSUE TITLE
how to generate summary statistics based on individual level data

### ISSUE THREAD

**Issue by zxy0912** [yuanzhongshang/GIFT#10]
Hi, I run individual level GIFT in simulations and it shows a good performance. However, when I tried to run summary statistics based GIFT on z-scores calculated by marginal linear regression and in-sample LD matrix, I failed to reproduce the results. From your answer to another issue, I think the summary stats based GIFT should produce similar results to individual level data based GIFT given in-sample LD. Could you provide a simple example which start from individual level data and generate similar results with z-scores generated from individual level data and in-sample LD? Thank you.

**Comment by yuanzhongshang** [comment]
Hi, 

Thank you for your attention. In our tutorial, we used the corresponding summary statistics to perform GIFT, and you can see a result similar to that from the individual-level data. Below, I show a simple way to convert individual-level data into summary statistics and perform GIFT.

```
library(GIFT)
dir <- "/net/mulan/disk2/luliuu/finemapping/github/20240117/GIFT-main"
#### load the directory containing the files to be processed only (e.g., plink binary format)
filelocation <- paste0(dir,"/example/simulation/individual/pre_process/plink_binary")
#### load the directory of plink exe file
plinkexe <- "plink-1.9"
#### pre-process the file to be a list including gene names vector, cis-genotype matrix and pindex
convert <- pre_process_individual(filelocation, plinkexe)
gene <- convert$gene
Zx <- convert$Z
pindex <- convert$pindex
load(paste0(dir, "/example/simulation/individual/individual_data.RData"))
result <- GIFT_individual(X, Y, Zx, Zy, gene, pindex, maxiter=1000, tol=1e-4, pleio=0, ncores=1)
> result
      gene causal_effect            p
1     CCNH    0.01209639 8.594982e-01
2    COX7C    0.02111053 8.028104e-01
3    RASA1    0.35309347 7.131827e-06
4 TMEM161B   -0.03306309 3.257628e-01

#### covert to the summary statistics
n1 <- dim(Zx)[1]
n2 <- dim(Zy)[1]
R=cor(X)
Zscore1 <- (t(Zx) %*% X)/sqrt(n1-1)
Zscore2 <- (t(Zy) %*% Y)/sqrt(n2-1)
LDmatrix1 <- cor(Zx)
LDmatrix2 <- cor(Zy)
result <- GIFT_summary(Zscore1, Zscore2, LDmatrix1, LDmatrix2, n1, n2, gene, pindex, R=R, maxiter=1000, tol=1e-4, pleio=0, ncores=1, in_sample_LD=T)
> result
      gene causal_effect            p
1     CCNH    0.01199365 8.604037e-01
2    COX7C    0.02108246 8.026706e-01
3    RASA1    0.35315823 7.087517e-06
4 TMEM161B   -0.03305883 3.257332e-01

```

Please let me know if you have any other questions.

Best,
Zhongshang

**Comment by zxy0912** [comment]
Thank you so much and it solves my question
