### ISSUE TITLE
您好，macos(M2)安装不上，不知道怎么处理

### ISSUE THREAD

**Issue by ka3533** [yuanzhongshang/GIFT#3]
ld: warning: search path '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0' not found
   ld: warning: search path '/opt/gfortran/lib' not found
   ld: library 'gfortran' not found
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [GIFT.so] Error 1
   ERROR: compilation failed for package ‘GIFT’
─  removing ‘/private/var/folders/31/c357rlzn6xv8pkf5g0vflq_r0000gn/T/RtmpY7uS5P/Rinst2f84f5a9420/GIFT’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'GIFT' from GitHub:
  ! System command 'R' failed

**Comment by yuanzhongshang** [comment]
Thank you for your attention, we noticed that some possible issues will occur when installing the package on the MacOS system. We have the detail explanation of the solution provided in "Installation" section of the [website](https://yuanzhongshang.github.io/GIFT/documentation/02_installation.html).
